/**
 * Api by SurpriseDesign
 * Api by SurpriseDesign 
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiBySurpriseDesign);
  }
}(this, function(expect, ApiBySurpriseDesign) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiBySurpriseDesign.ProjectApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectApi', function() {
    describe('appProjectCommentIdPut', function() {
      it('should call appProjectCommentIdPut successfully', function(done) {
        //uncomment below and update the code to test appProjectCommentIdPut
        //instance.appProjectCommentIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appProjectsGet', function() {
      it('should call appProjectsGet successfully', function(done) {
        //uncomment below and update the code to test appProjectsGet
        //instance.appProjectsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appProjectsIdDelete', function() {
      it('should call appProjectsIdDelete successfully', function(done) {
        //uncomment below and update the code to test appProjectsIdDelete
        //instance.appProjectsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appProjectsIdGet', function() {
      it('should call appProjectsIdGet successfully', function(done) {
        //uncomment below and update the code to test appProjectsIdGet
        //instance.appProjectsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appProjectsIdPut', function() {
      it('should call appProjectsIdPut successfully', function(done) {
        //uncomment below and update the code to test appProjectsIdPut
        //instance.appProjectsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appProjectsPost', function() {
      it('should call appProjectsPost successfully', function(done) {
        //uncomment below and update the code to test appProjectsPost
        //instance.appProjectsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
