/**
 * Api by SurpriseDesign
 * Api by SurpriseDesign 
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiBySurpriseDesign);
  }
}(this, function(expect, ApiBySurpriseDesign) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiBySurpriseDesign.UserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApi', function() {
    describe('appUsersGet', function() {
      it('should call appUsersGet successfully', function(done) {
        //uncomment below and update the code to test appUsersGet
        //instance.appUsersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appUsersIdDelete', function() {
      it('should call appUsersIdDelete successfully', function(done) {
        //uncomment below and update the code to test appUsersIdDelete
        //instance.appUsersIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appUsersIdGet', function() {
      it('should call appUsersIdGet successfully', function(done) {
        //uncomment below and update the code to test appUsersIdGet
        //instance.appUsersIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appUsersIdPut', function() {
      it('should call appUsersIdPut successfully', function(done) {
        //uncomment below and update the code to test appUsersIdPut
        //instance.appUsersIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appUsersPost', function() {
      it('should call appUsersPost successfully', function(done) {
        //uncomment below and update the code to test appUsersPost
        //instance.appUsersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
